# Structure du notebook

# Table des matières


1. Configuration et Import

Import des bibliothèques
Configuration des paramètres de visualisation
Chargement des données

2. Vue d'Ensemble des Données

Dimensions du dataset
Aperçu des premières lignes
Types de variables
Séparation variables catégorielles / numériques

3. Qualité des Données

Analyse des valeurs manquantes (visualisation)
Détection des doublons
Statistiques descriptives

4. Analyse Univariée

Variables Numériques : Histogrammes avec KDE
Variables Catégorielles : Diagrammes circulaires et barres
Variable Cible : Distribution et statistiques

5. Analyse Bivariée

Boxplots de la variable cible par variables catégorielles
Nuages de points pour relations numériques
Tests statistiques (ANOVA/Kruskal-Wallis)

6. Analyse des Corrélations

Matrice de corrélation (Pearson)
Heatmap interactive
Tests de significativité

7. Analyse Multivariée

Pairplot pour variables numériques
Analyse par région et autres groupes

8. Synthèse et Conclusions

Insights clés
Recommandations pour le preprocessing

# Configuration et Import

## Import des bibliothèques

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from scipy import stats
from scipy.stats import pearsonr, f_oneway, kruskal, chi2_contingency, spearmanr

## Configuration des paramètres de visualisation

## Chargement des données

In [3]:
url = "https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv"
df = pd.read_csv(url)  # adapter au chemin

# Data Overview

In [4]:
# Dimensions du dataset
print(f"Dimensions du dataset: {df.shape[0]} lignes × {df.shape[1]} colonnes\n")

Dimensions du dataset: 1338 lignes × 7 colonnes

In [5]:
# Aperçu des premières lignes
print("Aperçu des 10 premières lignes:")
df.head(10)

Aperçu des 10 premières lignes:

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [6]:
# Informations sur les colonnes
print("Informations sur les colonnes:")
df.info()

Informations sur les colonnes:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [7]:
# Séparation des variables selon le type
numerical_vars = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_vars = df.select_dtypes(include=['object', 'category']).columns.tolist()

#  Analyse Univariée

- Variables Numériques : Histogrammes avec KDE
- Variables Catégorielles : Diagrammes circulaires et barres
- Variable Cible : Distribution et statistiques

# Analyse Bivariée

- Boxplots de la variable cible par variables catégorielles
- Nuages de points pour relations numériques
- Tests statistiques (ANOVA/Kruskal-Wallis)

# Analyse des Corrélations

- Matrice de corrélation (Pearson)
- Heatmap interactive
- Tests de significativité

# Analyse Multivariée

- Pairplot pour variables numériques
- Analyse par région et autres groupes

# Synthèse et Conclusions

Insights clés
Recommandations pour le preprocessing

Le but est structurer le notebook. Tout ce qu'on aura à faire.

In [ ]:
df.shape

(1338, 7)

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

# 📊 Medical Cost Personal Dataset


## 🌍 Problématique globale

Dans un contexte où les dépenses de santé ne cessent d’augmenter, les compagnies d’assurance et les systèmes de santé cherchent à mieux comprendre les facteurs qui influencent les coûts médicaux. La question centrale est la suivante : **peut‑on prédire de manière fiable les charges médicales individuelles à partir de caractéristiques socio‑démographiques et comportementales ?**  
Ce problème est crucial car il permet non seulement d’anticiper les dépenses et d’ajuster les politiques tarifaires, mais aussi de mettre en évidence l’impact de variables comme l’âge, l’indice de masse corporelle, le tabagisme ou la région de résidence. L’objectif est donc de développer des modèles capables de traduire ces informations en estimations précises des coûts, afin d’améliorer la gestion des risques et la prise de décision dans le domaine de l’assurance santé.

## 📝 Description
Ce dataset contient des informations sur des bénéficiaires d’assurance santé aux États‑Unis, avec pour objectif de prédire les **coûts médicaux individuels** facturés par l’assurance.

## 📂 Structure du dataset
- **Nombre d’observations** : 1 338 lignes  
- **Nombre de variables** : 7 colonnes

### 🔑 Variables
- `age` : Âge du bénéficiaire principal  
- `sex` : Sexe du contractant (male / female)  
- `bmi` : Indice de masse corporelle (kg/m²)  
- `children` : Nombre d’enfants à charge couverts par l’assurance  
- `smoker` : Indique si le bénéficiaire est fumeur (yes / no)  
- `region` : Région de résidence aux États‑Unis (northeast, southeast, southwest, northwest)  
- `charges` : Coûts médicaux individuels facturés par l’assurance (variable cible)

## 🎯 Objectif
Construire des modèles de **régression** pour prédire les charges médicales.  

## 📌 Notes
- Les données sont **nettoyées et formatées** pour correspondre aux exemples du livre *Machine Learning with R* de Brett Lantz.  
- Licence : Open Database License (ODbL).

_________________

Nous définissons ci-dessous une structure de notre EDA. (les grandes lignes) et des pistes de réflexion.
- Penser à mettre les varaibles catégorielles d'une part et les numériques de l'autre
- Tests de normalité ?
- Tests de corrélartion ?
- Histogrammes, boxplots, etc.
- Diagramme circulaire pour les variables catégorielles : région, fumer ou non
- Test de "variance" entre catégorielle et notre variable cible
- Faire de commentaire sur les tendances qui se dessinnent dans notre cas.
- Voir ce que dit la littérature sur les insurance costs, les stats globales et sur les variables possibles qui peuvent nous aider.